name: Polyhedra-Combiner

on: 
  push: 
    branches: [main]

  pull_request:

jobs:
  
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Environment
      run: sudo apt install -y catch2

    - name: Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_CXX_COMPILER=clang++ ../
        cmake --build .

    - name: Test
      run: |
        cd build
        ctest .
  
