name: Polyhedra-Combiner

on: 
  push: 
    branches: [main, slim]

  pull_request:

jobs:
  
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Environment
      run: sudo apt install -y clang-11

    - name: Build
      run: |
        export TERM=xterm-color
        mkdir build && cd build
        cmake -DCMAKE_CXX_COMPILER=clang++ ../
        cmake --build . -- -j

    - name: Test
      run: |
        export TERM=xterm-color
        for test in build/tests/test*.run
        do
          ./${test} -d yes
        done

